// /**
//  * Creating a sidebar enables you to:
//  - create an ordered group of docs
//  - render a sidebar for each doc of that group
//  - provide next/previous navigation

//  The sidebars can be generated from the filesystem, or explicitly defined here.

//  Create as many sidebars as you want.
//  */

// // @ts-check

// /** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
// const sidebars = {
//   // By default, Docusaurus generates a sidebar from the docs folder structure
//   // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

//   // But you can create a sidebar manually

//   tutorialSidebar: [
//     'intro',
//     {
//       type: 'category',
//       label: 'Tutorial',
//       items: ['mariaDB/commands', 'mariaDB/install'],
//     },

//     {
//       type: 'category',
//       label: 'Tutorial2',
//       items: ['mariaDB/commands', 'mariaDB/install'],
//     },
//     {
//       type: 'link',
//       label: 'Learn more',
//       href: 'https://example.com',
//     },
//   ],
// };

// module.exports = sidebars;

const sidebars = {
  docs: [
    'intro',
    {
      type: 'category',
      label: 'Getting Started',
      link: {
        type: 'generated-index',
      },
      collapsed: false,
      items: [
        'mariaDB/install',
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      link: {
        type: 'generated-index',
        title: 'Docusaurus Guides',
        description:
          "Let's learn about the most important Docusaurus concepts!",
        keywords: ['guides'],
        image: '/img/docusaurus.png',
      },
      items: [
        'mariaDB/install',
        {
          type: 'category',
          label: 'Docs',
          link: {
            type: 'doc',
            id: 'mariaDB/install',
          },
          items: [
            'mariaDB/install',
            {
              type: 'category',
              label: 'Sidebar',
              link: {
                type: 'doc',
                id: 'mariaDB/install',
              },
              items: [
                'mariaDB/install',
              ],
            },
            'mariaDB/install',
          ],
        },
        'mariaDB/install',
        {
          type: 'category',
          label: 'Markdown Features',
          link: {
            type: 'doc',
            id: 'mariaDB/install',
          },
          items: [
            'mariaDB/install',
          ],
        },
        'mariaDB/install',
        {
          type: 'category',
          label: 'Internationalization',
          link: {type: 'doc', id: 'mariaDB/install'},
          items: [
            {
              type: 'doc',
              id: 'mariaDB/install',
              label: 'Tutorial',
            },
            {
              type: 'doc',
              id: 'mariaDB/install',
              label: 'Using Git',
            },
            {
              type: 'doc',
              id: 'mariaDB/install',
              label: 'Using Crowdin',
            },
          ],
        },
        'mariaDB/install'
      ],
    },
    {
      type: 'category',
      label: 'Advanced Guides',
      link: {type: 'doc', id: 'mariaDB/install'},
      items: [
        'mariaDB/install',
        
      ],
    },
    {
      type: 'category',
      label: 'Migrating from v1 to v2',
      items: [
        'mariaDB/install',
      ],
    },
  ],
};
module.exports = sidebars;
